import jsonpickle
from classProvider import netDevice
import re

#Take the master lsit of netowrk devices, encode it as json with json pickle and save it to a txt
def saveToInventoryFile(ListOfDevicesToSaveInInventoryFile,filename="inventory.json"):
    listAsJson = jsonpickle.encode(ListOfDevicesToSaveInInventoryFile)
    f = open(filename, "w")
    f.write(listAsJson)
    f.close()


#load the json file, deserialize it into a list of netowrk devcies, and chekc to amke sure all have username/password/secret
def loadInventoryFromFile(filename="inventory.json"):
    f = open(filename,"r")
    inventoryJson = f.read()
    objectsList = list[netDevice]
    if not inventoryJson == "":
        objectsList = jsonpickle.decode(inventoryJson)
    else:
        objectsList = []
    for dev in objectsList:
        if dev.username == "" or dev.password == "" or dev.secret == "":
            while True:
                usrInput = input("username for " + dev.managementAddress + ": ")
                if not usrInput == "":
                    dev.username = usrInput
                    break
                else:
                    print("Username cannot be blank.")
                
            while True:
                usrInput = input("Password for " + dev.managementAddress + ": ")
                if not usrInput == "":
                    dev.password = usrInput
                    break
                else:
                    print("Password cannot be blank.")
            while True:
                usrInput = input("Secret for " + dev.managementAddress + ": ")
                if not usrInput == "":
                    dev.secret = usrInput
                    break
                else:
                    print("Secret cannot be blank.")


    return objectsList.copy()




#export and csv of info about teh entwork devices
def exportInfoToCSV(devList: list[netDevice],inventoryFile: str):
    configsSet = False

    filePathParts = inventoryFile.split("\\")
    filePath = ""
    if len(filePathParts) > 1:
        for part in filePathParts[0:len(filePathParts ) - 1]:
            filePath += part + "\\"
    filePath += "Devices.csv"
    file = open(filePath,"w")
    for dev in devList:
        file.write("Hostname,Serial Number,OS,Number Of Interfaces,Up Time \n")
        line = (dev.hostName.replace(",","") + "," + dev.SerialNumber.replace(",","") + "," + dev.OS.replace(",","")  + "," + str(len(dev.ports))  + "," + dev.upTimeLastChecked.replace(",","") +  "\n")
        file.write(line)
        file.write("Interfaces,,,, \n")
        file.write("Name,Ip Address,Mask,Enabeled, \n")
        for p in dev.ports:
            line2 = f"{p.name},{p.ipAddress},{p.mask},{p.isUp}, \n"
            file.write(line2)
        file.write(",,,,, \n")

    
    file.close



def SaveConfigs(ListOfDevicesToSaveInInventoryFile: list[netDevice]):






    for device  in ListOfDevicesToSaveInInventoryFile:

        f = open(device.hostName + str(".ios"), "w")
        

        # Split the show run output into individual lines
        lines = device.config

        # Define a regular expression that matches user configuration commands
        user_config_regex = re.compile(r"^\S+\s+(\S+)\s+(.*)$") #regex Generated by OpenAI GPTChat

        # Iterate over the lines of the show run output
        for line in lines:
            # Use the regular expression to search for user configuration commands
            match = user_config_regex.search(line)
            if match:
                # If a user configuration command is found, print it
                command, arguments = match.groups()
                f.write(f"{command} {arguments}" + "\n")
        f.close()



